// next/src/components/hsk/hide-buttons.tsx
type HideBtnsType = {
  hideChinese: boolean;
  hideRussian: boolean;
  hidePinyin: boolean;
  setHideChinese: Function;
  setHideRussian: Function;
  setHidePinyin: Function;
};

export default function HideButtons({
  hideChinese,
  hideRussian,
  hidePinyin,
  setHideChinese,
  setHideRussian,
  setHidePinyin,
}: HideBtnsType) {
  const btns = [
    {
      txt: "Скрыть:",
      flag: false,
      func: () => {},
      disabled: "disabled",
    },
    {
      txt: "Иероглифы",
      flag: hideChinese,
      func: setHideChinese,
      disabled: "",
    },
    {
      txt: "Пиньинь",
      flag: hidePinyin,
      func: setHidePinyin,
      disabled: "",
    },
    {
      txt: "Перевод",
      flag: hideRussian,
      func: setHideRussian,
      disabled: "",
    },
  ];

  return (
    <div>
      <span className='btn-group mb-2 float-start' role='group'>
        {btns.map(({ txt, flag, func, disabled }) => (
          <button
            key={txt}
            className={`btn btn-sm btn-${flag ? "" : "outline-"}info ${disabled}`}
            type='button'
            onClick={() => func(!flag)}
          >
            {txt}
          </button>
        ))}
      </span>
    </div>
  );
}

// qwik/src/components/hsk/hide-buttons.tsx
import { component$, type Signal } from '@builder.io/qwik';

type HideBtnsProps = {
  hideBtnsSig: Signal<string[]>;
};

export enum HideBtnsEnum {
  cn = 'Иероглифы',
  ru = 'Перевод',
  py = 'Пиньинь',
}

export const HideButtons = component$(({ hideBtnsSig }: HideBtnsProps) => {
  const btns = [HideBtnsEnum.cn, HideBtnsEnum.py, HideBtnsEnum.ru];

  return (
    <div class="float-left mb-2 text-base-content">
      <span class={'font-bold mr-1'}>Скрыть: </span>

      <div class="btn-group">
        {btns.map((txt: string, ind: number) => (
          <button
            key={ind}
            class={`btn btn-sm btn-outline btn-info lowercase ${
              hideBtnsSig.value.includes(txt) ? 'btn-active' : ''
            }`}
            onClick$={() => {
              hideBtnsSig.value = hideBtnsSig.value.includes(txt)
                ? hideBtnsSig.value.filter((x) => x !== txt)
                : [...hideBtnsSig.value, txt];
            }}
          >
            {txt}
          </button>
        ))}
      </div>
    </div>
  );
});
