// next/src/components/hsk/old-hsk-table-row.tsx
"use client";
import { v4 as uuid } from "uuid";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMinus, faPlay, faPlus } from "@fortawesome/free-solid-svg-icons";
import constUrls from "../../helpers/constants/urls";
import { useAlertCtx } from "../../context/alerts/store";
import { useHskCtx } from "../../context/hsk/store";
import { addUserHskWord, removeUserHskWord } from "../../context/hsk/actions";
import CONSTANTS from "../../helpers/constants/consts";

type TableRowType = {
  word: OldHskWordType;
  hideChinese: boolean;
  hidePinyin: boolean;
  hideRussian: boolean;
  userSelected: boolean;
};

export default function OldHskTableRow({
  word,
  hideChinese,
  hidePinyin,
  hideRussian,
  userSelected,
}: TableRowType) {
  const { chinese: cn, pinyin: py, translation: ru, word_id: id, level: lvl } = word;
  const { alerts, setAlerts } = useAlertCtx();
  const { userHsk2Words, setUserHsk2Words } = useHskCtx();
  const pronounce = (id: number, lvl: number) => {
    const o: { [key: number]: number } = {
      1: id - 1,
      2: id - 151,
      3: id - 301,
      4: id - 601,
      5: id - 1201,
      6: id - 2501,
    };
    const wordId = o[lvl];
    new Audio(`${constUrls.myAudioURL}hsk${lvl}/${wordId}.mp3`).play();
  };

  const addOrRemoveHskWord = () => {
    const id = uuid();
    const token = localStorage.token;
    if (!token) {
      return setAlerts([...alerts, { id, bgColor: "danger", txt: "Нужно авторизоваться" }]);
    }

    if (userSelected) {
      setUserHsk2Words(userHsk2Words.filter((x) => x.word_id !== word.word_id));
      removeUserHskWord(word.word_id, token);
      return setAlerts([
        ...alerts,
        { id, bgColor: "warning", txt: "Слово удалено из вашего словарика" },
      ]);
    }

    if (userHsk2Words.length >= CONSTANTS.users.vocabSize) {
      return setAlerts([
        ...alerts,
        {
          id,
          bgColor: "danger",
          txt: `Нет! В вашем словарике HSK уже ${CONSTANTS.users.vocabSize} слов!`,
        },
      ]);
    }

    addUserHskWord(word, token);
    setUserHsk2Words([...userHsk2Words, word]);
    setAlerts([...alerts, { id, bgColor: "success", txt: "Слово добавлено в ваш словарик" }]);
  };

  return (
    <>
      <tr className={userSelected ? "table-secondary" : ""}>
        <td className='small'>{id}</td>
        {!hideChinese && (
          <td>
            <h5>{cn}</h5>
          </td>
        )}
        {!hidePinyin && <td>{py}</td>}
        {!hideRussian && <td className='small'>{ru}</td>}
        <td>
          <button className='btn btn-sm btn-info' onClick={() => pronounce(id, lvl)}>
            <FontAwesomeIcon icon={faPlay} />
          </button>
        </td>
        <td>
          <button
            className={userSelected ? "btn btn-sm btn-warning" : "btn btn-sm btn-info"}
            onClick={addOrRemoveHskWord}
          >
            {userSelected ? <FontAwesomeIcon icon={faMinus} /> : <FontAwesomeIcon icon={faPlus} />}
          </button>
        </td>
      </tr>
    </>
  );
}

// qwik/src/components/hsk/old-hsk-table-row.tsx
import { component$, $, useSignal, useContext, type Signal } from "@builder.io/qwik";
import CONST_URLS from "~/misc/consts/urls";
import CONSTANTS from "~/misc/consts/consts";
import type { OldHskWordType } from "~/routes/hsk/2/table";
import Cookies from "js-cookie";
import { ApiService } from "~/misc/actions/request";
import { alertsContext } from "~/root";
import { minusSvg, plusSvg, playSvg } from "../common/media/svg";
import { HideBtnsEnum } from "./hide-buttons";

type TableRowType = {
  word: OldHskWordType;
  hideBtnsSig: Signal<string[]>;
  userSelected: boolean;
  userWordsLen: number;
  isPrivate?: boolean;
};

export const pronounce = (id: number, lvl: number) => {
  const o: { [key: number]: number } = {
    1: id - 1,
    2: id - 151,
    3: id - 301,
    4: id - 601,
    5: id - 1201,
    6: id - 2501,
  };
  const wordId = o[lvl];
  new Audio(`${CONST_URLS.myAudioURL}hsk${lvl}/${wordId}.mp3`).play();
};

export const addUserHskWord = async (word: OldHskWordType, token: string) => {
  await ApiService.post("/api/words/", word, token);
};

export const removeUserHskWord = async (wordId: number, token: string) => {
  await ApiService.delete("/api/words/" + wordId, token);
};

export const OldHskTableRow = component$(
  ({ word, hideBtnsSig, userSelected: clickedByUser, userWordsLen, isPrivate }: TableRowType) => {
    const userSelectedSignal = useSignal(clickedByUser);
    const userSelected = userSelectedSignal.value && !isPrivate;
    const userWordsLenSignal = useSignal(userWordsLen);

    const alertsState = useContext(alertsContext);

    const { chinese: cn, pinyin: py, translation: ru, word_id: id, level: lvl } = word;

    const addOrRemoveHskWord = $(async () => {
      const token = Cookies.get("token");

      // console.log(userWordsLenSignal.value);
      if (!token) {
        return alertsState.push({ bg: "alert-error", text: "Нужно войти" });
      }

      if (userSelectedSignal.value) {
        removeUserHskWord(word.word_id, token);
        userWordsLenSignal.value--;
        userSelectedSignal.value = !userSelectedSignal.value;
        return alertsState.push({ bg: "alert-info", text: "Слово удалено из вашего словарика" });
      }

      if (userWordsLenSignal.value >= CONSTANTS.users.vocabSize) {
        return alertsState.push({
          bg: "alert-error",
          text: `Лимит ${CONSTANTS.users.vocabSize} слов!`,
        });
      }

      addUserHskWord(word, token);
      userWordsLenSignal.value++;
      userSelectedSignal.value = !userSelectedSignal.value;
      return alertsState.push({ bg: "alert-success", text: "Слово добавлено в ваш словарик" });
    });

    return (
      <>
        <tr class={"hover"}>
          <td class={userSelected ? "bg-secondary" : ""}>{id}</td>
          {!hideBtnsSig.value.includes(HideBtnsEnum.cn) && (
            <td class={`prose ${userSelected ? "bg-secondary" : ""}`}>
              <h2>{cn}</h2>
            </td>
          )}
          {!hideBtnsSig.value.includes(HideBtnsEnum.py) && (
            <td class={userSelected ? "bg-secondary" : ""}>{py}</td>
          )}
          {!hideBtnsSig.value.includes(HideBtnsEnum.ru) && (
            <td class={userSelected ? "bg-secondary" : ""} style={{ maxWidth: "50%" }}>
              <div style={{ wordWrap: "break-word", whiteSpace: "normal" }}>{ru}</div>
            </td>
          )}
          <td class={userSelected ? "bg-secondary" : ""}>
            <button class='btn btn-sm btn-info' onClick$={() => pronounce(id, lvl)}>
              {playSvg}
            </button>
          </td>
          <td class={userSelected ? "bg-secondary" : ""}>
            {userSelectedSignal.value ? (
              <button class='btn btn-sm btn-warning' onClick$={addOrRemoveHskWord}>
                {minusSvg}
              </button>
            ) : (
              <button class='btn btn-sm btn-info' onClick$={addOrRemoveHskWord}>
                {plusSvg}
              </button>
            )}
          </td>
        </tr>
      </>
    );
  }
);
