// next/src/components/start/pinyin-tests.tsx
"use client";
import { ChangeEvent, useState, useEffect } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSyncAlt, faPlay } from "@fortawesome/free-solid-svg-icons";

import { allPinyinSounds } from "../../helpers/constants/pinyin";
import { playAudio } from "./play-audio";
import { getRandElem } from "../../helpers/tools";

type AnswersObj = {
  [key: string]: string;
};

const separator = "_";

export default function PinyinTests() {
  const columns = [1, 2, 3];
  const answers = [1, 2, 3, 4]; // 4 per column
  const answersNum = columns.length * answers.length;

  const [inputs, setInputs] = useState<AnswersObj>({});
  const [sounds, setSounds] = useState([""]);

  useEffect(() => {
    init();
  }, []);

  function getRandAnswers(): string[] {
    const sounds: string[] = [];
    while (sounds.length < answersNum) {
      // const randSound = allPinyinSounds[Math.floor(Math.random() * allPinyinSounds.length)];
      const randSound = getRandElem(allPinyinSounds);
      if (!sounds.includes(randSound)) {
        sounds.push(randSound);
      }
    }
    return sounds;
  }

  function init() {
    const randSounds = getRandAnswers();
    setSounds(randSounds);
    setInputs(setEmptyAnswers(randSounds));
    setTimeout(() => {
      for (let i = 0; i < randSounds.length; i++) {
        const ansBtn = document.getElementById(randSounds[i]);
        ansBtn?.classList.remove("bg-success", "bg-danger", "bg-warning");
        const userInput = document.getElementById(getInputId(randSounds[i])) as HTMLInputElement;
        if (userInput) userInput.value = "";
      }
    }, 300);
  }

  function getInputId(sound: string): string {
    return `${separator}${sound}`;
  }

  function setEmptyAnswers(answers: string[]): AnswersObj {
    const ansObj: AnswersObj = {};
    answers.forEach((sound) => {
      ansObj[getInputId(sound)] = "";
    });
    return ansObj;
  }

  function checkAnswers() {
    for (let i = 0; i < sounds.length; i++) {
      const answer = sounds[i];
      const userInput = inputs[getInputId(answer)];
      const ansBtn = document.getElementById(answer);
      ansBtn?.classList.add(userInput === answer ? "bg-success" : "bg-danger");
    }
  }

  const showAnswers = () => {
    for (let i = 0; i < sounds.length; i++) {
      const ans = sounds[i];
      const ansBtn = document.getElementById(ans);
      ansBtn?.classList.remove("bg-success", "bg-danger");
      ansBtn?.classList.add("bg-warning");
      const userInput = document.getElementById(getInputId(ans)) as HTMLInputElement;
      if (userInput) userInput.value = ans;
    }
  };

  const receiveAnswer = (e: ChangeEvent<HTMLInputElement>) => {
    const target = e.target;
    setInputs({ ...inputs, [target.id]: target.value });
  };

  const buttons = [
    {
      func: checkAnswers,
      txt: "Проверить",
    },
    {
      func: showAnswers,
      txt: "Показать Ответы",
    },
    {
      func: init,
      txt: <FontAwesomeIcon icon={faSyncAlt} />,
    },
  ];

  return (
    <>
      <div className='row my-2'>
        {columns.map((col, k) => (
          <div className='col-sm-4' key={col}>
            {answers.map((quest, i) => (
              <div className='input-group my-2' key={quest}>
                <button
                  className='btn btn-secondary'
                  id={sounds[i + answers.length * k]}
                  type='button'
                  onClick={() => playAudio(sounds[i + answers.length * k])}
                >
                  <FontAwesomeIcon icon={faPlay} />
                  {/* {sounds[i + answers.length * k]} */}
                </button>

                <input
                  type='text'
                  className='form-control'
                  id={getInputId(sounds[i + answers.length * k])}
                  onChange={(e) => receiveAnswer(e)}
                />
              </div>
            ))}
          </div>
        ))}
      </div>

      <div>
        {buttons.map(({ func, txt }, ind) => (
          <button type='button' className='btn btn-primary btn-sm me-1' onClick={func} key={ind}>
            {txt}
          </button>
        ))}
      </div>
    </>
  );
}

// qwik/src/components/start/pinyin-tests/pinyin-tests.tsx
import { component$, useVisibleTask$, $, useStore } from "@builder.io/qwik";
import { playSvg, rewindSvg } from "~/components/common/media/svg";
import { allPinyinSounds } from "~/misc/consts/pinyin";
import CONST_URLS from "~/misc/consts/urls";
import { getRandElem } from "~/misc/helpers/tools";

type AnswersObj = {
  [key: string]: string;
};

type StoreAns = {
  sounds: string[];
  inputs: AnswersObj;
};

const separator = "_";
export const columns = [1, 2, 3];
export const answers = [1, 2, 3, 4]; // 4 per column
const answersNum = columns.length * answers.length;

function getRandAnswers(tones?: string[]): string[] {
  const sounds: string[] = [];
  while (sounds.length < answersNum) {
    const randSound = getRandElem(allPinyinSounds);
    if (typeof randSound !== "string" || sounds.includes(randSound)) continue;
    if (Array.isArray(tones) && !tones.includes(randSound?.charAt(randSound?.length - 1))) {
      continue;
    }

    sounds.push(randSound);
  }
  return sounds;
}

export const playAudio = (target: string) => {
  new Audio(`${CONST_URLS.myAudioURL}pinyin/${target}.mp3`).play();
};

export function init(store: StoreAns, tones?: string[]) {
  const randSounds = getRandAnswers(tones);
  store.sounds = randSounds;
  store.inputs = setEmptyAnswers(randSounds);
  setTimeout(() => {
    for (let i = 0; i < randSounds.length; i++) {
      const ansBtn = document.getElementById(randSounds[i]);
      ansBtn?.classList.remove("bg-success", "bg-error", "bg-warning");
      const userInput = document.getElementById(getInputId(randSounds[i])) as HTMLInputElement;
      if (userInput) userInput.value = "";
    }
  }, 300);
}

export function getInputId(sound: string): string {
  return `${separator}${sound}`;
}

export function setEmptyAnswers(answers: string[]): AnswersObj {
  const ansObj: AnswersObj = {};
  answers.forEach((sound) => {
    ansObj[getInputId(sound)] = "";
  });
  return ansObj;
}

export const PinyinTests = component$(({ tones }: { tones?: string[] }) => {
  const store = useStore<StoreAns>({ sounds: [""], inputs: {} });

  useVisibleTask$(() => {
    init(store, tones);
  });

  const checkAnswers = $(() => {
    for (let i = 0; i < store.sounds.length; i++) {
      const answer = store.sounds[i];
      const userInput = store.inputs[getInputId(answer)].toLowerCase().trim();
      const ansBtn = document.getElementById(answer);
      ansBtn?.classList.add(userInput === answer ? "bg-success" : "bg-error");
    }
  });

  const showAnswers = $(() => {
    for (let i = 0; i < store.sounds.length; i++) {
      const ans = store.sounds[i];
      const ansBtn = document.getElementById(ans);
      ansBtn?.classList.remove("bg-success", "bg-error");
      ansBtn?.classList.add("bg-warning");
      const userInput = document.getElementById(getInputId(ans)) as HTMLInputElement;
      if (userInput) userInput.value = ans;
    }
  });

  const receiveAnswer = $((e: Event) => {
    const target = e.target as HTMLTextAreaElement;
    store.inputs = { ...store.inputs, [target!.id]: target!.value };
  });

  const buttons = [
    {
      func: checkAnswers,
      txt: "Проверить",
    },
    {
      func: showAnswers,
      txt: "Показать Ответы",
    },
    {
      func: $(() => init(store, tones)),
      txt: rewindSvg,
    },
  ];

  return (
    <>
      <div class='prose mb-1 mt-3'>
        <h4>{tones ? `Только ${tones.join(" и ")}` : "Все"} тоны</h4>
      </div>
      <div class='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3'>
        {columns.map((col, k) => (
          <div class='w-full' key={col}>
            {answers.map((_quest, i) => (
              <div class='form-control my-2 pr-2' key={i}>
                <label class='input-group'>
                  <button
                    class='btn btn-info'
                    id={store.sounds[i + answers.length * k]}
                    type='button'
                    onClick$={() => playAudio(store.sounds[i + answers.length * k])}
                  >
                    {playSvg}
                  </button>
                  <input
                    type='text'
                    placeholder='...'
                    class='input input-bordered w-full'
                    id={getInputId(store.sounds[i + answers.length * k])}
                    onInput$={receiveAnswer}
                  />
                </label>
              </div>
            ))}
          </div>
        ))}
      </div>
      <div class='flex'>
        {buttons.map(({ func, txt }, ind) => (
          <button type='button' class='btn btn-primary btn-sm mr-1' key={ind} onClick$={func}>
            {txt}
          </button>
        ))}
      </div>
    </>
  );
});
