// qwik/src/components/hsk/flip-cards.tsx
import { component$ } from "@builder.io/qwik";
import { type OldHskWordType } from "~/routes/hsk/2/table";
import { FlipCard } from "./flip-card";
import { type PinyinAboveStore } from "./hsk-table";

export const FlipCards = component$(
  ({ words, pinyinAbove }: { words: OldHskWordType[]; pinyinAbove: PinyinAboveStore }) => {
    return (
      <>
        <div class=' grid grid-cols-2 md:grid-cols-4 gap-4'>
          {words &&
            words.map((word) => (
              <FlipCard word={word} key={word._id} pinyinAbove={pinyinAbove.bool} />
            ))}
        </div>
      </>
    );
  }
);

// next/src/components/hsk/flip-cards.tsx
import { useState, useEffect } from "react";
import FlipCard from "./flip-card";

export default function FlipCards({ words }: { words: OldHskWordType[] }) {
  const [pinyinAbove, setPinyinAbove] = useState(false);

  useEffect(() => {
    if (+localStorage.pinyinAbove) {
      setPinyinAbove(true);
    } else {
      setPinyinAbove(false);
    }
  });
  return (
    <>
      <div>
        <span className='btn-group mb-2' role='group'>
          <button className={`btn btn-sm btn-outline-info disabled`} type='button'>
            Сверху отображать:
          </button>
          <button
            className={`btn btn-sm btn-${pinyinAbove ? "outline-" : ""}info`}
            type='button'
            onClick={() => {
              localStorage.setItem("pinyinAbove", "0");
              setPinyinAbove(false);
            }}
          >
            Иероглифы
          </button>

          <button
            type='button'
            className={`btn btn-sm btn-${pinyinAbove ? "" : "outline-"}info`}
            onClick={() => {
              localStorage.setItem("pinyinAbove", "1");
              setPinyinAbove(true);
            }}
          >
            Пиньинь
          </button>
        </span>
      </div>
      <div className='row'>
        {words &&
          words.map((word) => <FlipCard word={word} key={word._id} pinyinAbove={pinyinAbove} />)}
      </div>
    </>
  );
}
