// qwik/src/components/hsk/table-or-cards-btns.tsx
import { component$, useVisibleTask$ } from '@builder.io/qwik';
import { type DisplayCardsStore } from './hsk-table';

export const TableOrCardsBtns = component$(
  ({ displayCards }: { displayCards: DisplayCardsStore }) => {
    useVisibleTask$(() => {
      displayCards.bool = !!+localStorage.displayCards;
    });

    return (
      <div class={'sm:float-right float-left mb-2'}>
        <span class={'mr-1 font-bold'}>Отображать: </span>
        <div class="btn-group">
          <button
            class={`btn btn-sm btn-info lowercase ${displayCards.bool ? 'btn-outline' : ''}`}
            type="button"
            onClick$={() => {
              localStorage.setItem('displayCards', '0');
              displayCards.bool = false;
            }}
          >
            Таблицей
          </button>

          <button
            type="button"
            class={`btn btn-sm btn-info lowercase ${displayCards.bool ? '' : 'btn-outline'}`}
            onClick$={() => {
              localStorage.setItem('displayCards', '1');
              displayCards.bool = true;
            }}
          >
            Карточками
          </button>
        </div>
      </div>
    );
  },
);

// next/src/components/hsk/table-or-cards-btns.tsx
import { useEffect } from "react";

type TableOrCardsBtnsProps = {
  setDisplayCards: Function;
  displayCards: boolean;
};

export default function TableOrCardsBtns({ setDisplayCards, displayCards }: TableOrCardsBtnsProps) {
  useEffect(() => {
    if (+localStorage.displayCards) {
      setDisplayCards(true);
    } else {
      setDisplayCards(false);
    }
  }, [displayCards]);

  return (
    <div className=''>
      <span className='btn-group mb-2 float-end' role='group'>
        <button className={`btn btn-sm btn-outline-info disabled`} type='button'>
          Отображать:
        </button>
        <button
          className={`btn btn-sm btn-${displayCards ? "outline-" : ""}info`}
          type='button'
          onClick={() => {
            localStorage.setItem("displayCards", "0");
            setDisplayCards(false);
          }}
        >
          Таблицей
        </button>

        <button
          type='button'
          className={`btn btn-sm btn-${displayCards ? "" : "outline-"}info`}
          onClick={() => {
            localStorage.setItem("displayCards", "1");
            setDisplayCards(true);
          }}
        >
          Карточками
        </button>
      </span>
    </div>
  );
}
