// next/app/hsk/3/table/page.tsx
"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { apiGetReq } from "../../../../src/helpers/api";

import TableCard from "../../../../src/components/hsk/table-card";
import Pagination from "../../../../src/components/hsk/pagination";
import HskTable from "../../../../src/components/hsk/hsk-table";

export default function Hsk3TablePage() {
  const searchParams = useSearchParams();
  const [level, setLevel] = useState("1");
  const [limit, setLimit] = useState(0);
  const [hskWords, setHskWords] = useState<NewHskWordType[] | null>(null);

  useEffect(() => {
    const lvl = searchParams.get("lvl") || "1";
    const pageParam = searchParams.get("pg");
    const lmt = pageParam ? +pageParam : 0;

    setLimit(lmt);
    setLevel(lvl);
    loadLexicon(lvl, lmt);
  }, []);

  async function loadLexicon(lvl: string, lmt: number) {
    setHskWords(null);

    try {
      const data = await apiGetReq(`/api/newhskwords?hsk_level=${lvl}&limit=${lmt}`);
      if (data.length > 0) setHskWords(data);
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <>
      <div className='row'>
        <div className='col-sm-3'>
          <TableCard level={level} setLevel={setLevel} isOldHsk={false} isForTests={false} />
        </div>

        <div className='col-sm-9'>
          <h1>Вся лексика для HSK 3</h1>
          <Pagination level={level} setLimit={setLimit} curPage={limit} isOldHsk={false} />
          <HskTable isOldHsk={false} hskWords={hskWords} />
        </div>
      </div>
    </>
  );
}

// qwik/src/routes/hsk/3/table/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, useLocation } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import { TableCard } from "~/components/hsk/table-card";
import { Pagination } from "~/components/hsk/pagination";
import { ApiService } from "~/misc/actions/request";
import { NewHskTable } from "~/components/hsk/new-hsk-table";
import { PageTitle } from "~/components/common/layout/title";
import { FlexRow } from "~/components/common/layout/flex-row";
import { Sidebar } from "~/components/common/layout/sidebar";
import { MainContent } from "~/components/common/layout/main-content";
import { PhoneticsLinkCard } from "~/components/common/content-cards/phonetics-link-card";
import { CharactersLinkCard } from "~/components/common/content-cards/characters-link-card";

export type NewHskWordType = {
  _id: ObjectId;
  id: number;
  cn: string;
  py: string;
  ru: string;
  lvl: string;
};

export const getHskWords = routeLoader$(async (ev): Promise<NewHskWordType[]> => {
  const lvl = ev.query.get("lvl") || "1";
  const lmt = ev.query.get("pg") || "0";
  return await ApiService.get(`/api/newhskwords?hsk_level=${lvl}&limit=${lmt}`, undefined, []);
});

export default component$(() => {
  const loc = useLocation();
  const hskWords = getHskWords();

  return (
    <>
      <PageTitle txt={"Вся лексика для HSK 3.0"} />

      <FlexRow>
        <Sidebar>
          <TableCard
            level={loc.url.searchParams.get("lvl") || "1"}
            isOldHsk={false}
            isForTests={false}
          />
          <PhoneticsLinkCard />
          <CharactersLinkCard />
        </Sidebar>

        <MainContent>
          <Pagination
            level={loc.url.searchParams.get("lvl") || "1"}
            curPage={+loc.url.searchParams.get("pg")! || 0}
            isOldHsk={false}
          />

          <NewHskTable hskWords={hskWords?.value || []} />
        </MainContent>
      </FlexRow>
    </>
  );
});

export const head: DocumentHead = {
  title: "Chinese+ Лексика HSK 3.0",
  meta: [
    {
      name: "description",
      content: "Все слова нового HSK версии 3.0 разбитые по уровням.",
    },
  ],
};
