// next/app/contacts/page.tsx
import Link from "next/link";
import { faTelegram, faVk, faYoutube } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export default function Contacts() {
  return (
    <div>
      <h2>Пойти на Контакт</h2>
      <p>
        Telegram: <code>@sinokislov</code>
        <br />
        Email: <code>sinokislov@gmail.com</code>
      </p>
      <p>
        Вы также можете просто писать здесь в <Link href='/posts'>Гостевой</Link> или в любом месте
        на сайте.
        <br />
        Любой комментарий с сайта сразу поступает в мой телеграм.
      </p>
      <p>
        Если хотите показать скриншот с багом, то лучше сразу в почту или телеграм писать. Спасибо!
      </p>

      <h4>О Нас</h4>

      <p className=''>
        <span className=''>
          Проект делают 2 человека. С нами можно связаться и в соцсетях (быстрее в Телеграме):{" "}
          <Link href='https://t.me/chineseplusnew' target={"_blank"}>
            <FontAwesomeIcon icon={faTelegram} className='iconSize mx-1' />
          </Link>{" "}
          <Link href='https://vk.com/buyilehu' target={"_blank"}>
            <FontAwesomeIcon icon={faVk} className='iconSize mx-1' />
          </Link>{" "}
          <Link href='https://www.youtube.com/c/Buyilehuorg' target={"_blank"}>
            <FontAwesomeIcon icon={faYoutube} className='iconSize mx-1' />
          </Link>
        </span>
        <br /> У нас также еще жив{" "}
        <Link href='https://www.chineseplus.ru/' target={"_blank"}>
          наш старый сайт.
        </Link>
      </p>
    </div>
  );
}

// qwik/src/routes/contacts/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, Link } from "@builder.io/qwik-city";
import { FlexRow } from "~/components/common/layout/flex-row";
import { MainContent } from "~/components/common/layout/main-content";
import { PageTitle } from "~/components/common/layout/title";

export default component$(() => {
  return (
    <>
      <PageTitle txt={"Пойти на контакт"} />

      <FlexRow>
        <MainContent>
          <div class='prose'>
            <p>
              Телеграм админа: <code>@sinokislov</code>
              <br />
              Почта: <code>sinokislov@gmail.com</code>
              <br />
              Быстрее реагирую на телеграм или комментарии здесь на сайте.
            </p>
            <h3>О нас</h3>
            <p>
              Проект делают 2 человека: Александр (разработка) и Вэйи (китайский язык).
              <br />
              Также еще жив наш старый{" "}
              <Link href='http://chineseplus.ru/' target='_blank'>
                сайт
              </Link>
              .
            </p>
          </div>
        </MainContent>
      </FlexRow>
    </>
  );
});

export const head: DocumentHead = {
  title: "Chinese+ Контакты",
  meta: [
    {
      name: "description",
      content: "Кто мы и как с нами связаться",
    },
  ],
};
