// next/app/hsk/2/search/page.tsx
"use client";
import { useState } from "react";
import HskTable from "../../../../src/components/hsk/hsk-table";
import HskSearchForm from "../../../../src/components/hsk/search-form";
import { apiPostReq } from "../../../../src/helpers/api/request";

export default function Hsk2Search({}) {
  const [hskWords, setHskWords] = useState<NewHskWordType[] | null>(null);
  const [chineseWord, setChineseWord] = useState("");

  const onSubmit = async () => {
    setHskWords(null);

    if (chineseWord) {
      try {
        const data = await apiPostReq("/api/lexicon/search", { chinese: chineseWord });
        if (data.length > 0) setHskWords(data);
      } catch (err) {
        console.log(err);
      }
    }
  };

  return (
    <div className='row'>
      <div className='col-sm-3'>
        <div className='card border-primary mb-3'>
          <div className='card-body'>
            <h4 className='card-title'>Поиск слов HSK 2</h4>
            <h6 className='card-subtitle mb-2 text-muted'>Вся лексика</h6>
            <p className='card-text'>Найдите нужные вам слова HSK (любые из 5 000 слов)</p>
          </div>
        </div>
      </div>

      <div className='col-sm-9'>
        <h1>Поиск слов HSK 2</h1>
        <HskSearchForm onSubmit={onSubmit} setChineseWord={setChineseWord} />
        <HskTable isOldHsk={true} hskWords={hskWords} />
      </div>
    </div>
  );
}

// qwik/src/routes/hsk/2/search/index.tsx
import { component$, useSignal } from "@builder.io/qwik";
import { OldHskTable } from "~/components/hsk/hsk-table";
import { HskSearchForm } from "~/components/hsk/search-form";
import { type OldHskWordType } from "../table";

import { FlexRow } from "~/components/common/layout/flex-row";
import { Sidebar } from "~/components/common/layout/sidebar";
import { MainContent } from "~/components/common/layout/main-content";
import { PageTitle } from "~/components/common/layout/title";
import { type DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  const hskWords = useSignal<OldHskWordType[]>([]);

  return (
    <>
      <PageTitle txt={"Поиск слов HSK 2.0"} />
      <FlexRow>
        <Sidebar>
          <div class='card bg-primary text-primary-content'>
            <div class='card-body'>
              <h2 class='card-title'>Найти слово HSK 2.0</h2>
              <p>Введите иероглиф (часть слова) или слово целиком (любые из 5 000 слов)</p>
              <HskSearchForm hskWords={hskWords} isOldHsk={true} />
            </div>
          </div>
        </Sidebar>

        <MainContent>
          <OldHskTable hskWords={hskWords?.value || []} userHskWords={[]} />
        </MainContent>
      </FlexRow>
    </>
  );
});

export const head: DocumentHead = {
  title: "Chinese+ Поиск по словам HSK 2.0",
};
